### ISSUE TITLE
Is there any further advancement?

### ISSUE THREAD

**Issue by Carlos-Henreis** [charuj/multigraph_lstm_hyperparamsearch#1]
I'm very interested in the part of optimization of hyperparametros with tensorflow ... I found this repository, but it seems that it is abandoned

**Comment by charuj** [comment]
Hey @Carlos-Henreis , it's not abandoned per se, this version of parameter search works for me in its current state. Admittedly, there are now probably built-ins in Tensorflow that help with optimization, I haven't looked into that. There are also new papers that have come out on better ways to do search (vs. random search)

**Comment by Carlos-Henreis** [comment]
- First of all, thank you very much for your feedback.

- Yes, but for example you can improve your implementation by using Pre-made [Estimators](https://www.tensorflow.org/programmers_guide/estimators)

- I still think that Random Search is still the state of art (by its simplicity and the ease of paralyzing things and good results) and because of that [paper](http://www.jmlr.org/papers/volume13/bergstra12a/bergstra12a.pdf).

- I recently researched a lot and found very little about the optimization of hyperparameters in tensorflow .... Your approach was the one that pleased me the most :). Maybe I will work with it this week, if I make any progress, can I contribute with this repository (with examples, implementations of other models, definitions, etc.)?
